CREATE DATABASE IF NOT EXISTS barbertrack
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE barbertrack;

CREATE TABLE barbearia (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome_fantasia VARCHAR(100) NOT NULL,
    razao_social VARCHAR(150) NOT NULL,
    cnpj CHAR(14) NOT NULL,
    email VARCHAR(100) NULL,
    telefone VARCHAR(20) NULL,
    senha CHAR(60) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE cliente (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    barbearia_id INT UNSIGNED NOT NULL,
    nome VARCHAR(80) NOT NULL,
    sobrenome VARCHAR(80) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NULL,
    senha CHAR(60) NOT NULL,
    observacao VARCHAR(255) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (barbearia_id) REFERENCES barbearia(id)
);

CREATE TABLE barbeiro (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    barbearia_id INT UNSIGNED NOT NULL,
    nome VARCHAR(80) NOT NULL,
    sobrenome VARCHAR(80) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(100) NULL,
    telefone VARCHAR(20) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (barbearia_id) REFERENCES barbearia(id)
);

CREATE TABLE reset_senha (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  tipo ENUM('cliente', 'barbearia') NOT NULL,
  token CHAR(64) NOT NULL,
  expira_em DATETIME NOT NULL,
  usado BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servico (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  barbearia_id INT UNSIGNED NOT NULL,
  nome VARCHAR(100) NOT NULL,
  duracao_min INT NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (barbearia_id) REFERENCES barbearia(id)
);

CREATE TABLE agendamento (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  barbearia_id INT UNSIGNED NOT NULL,
  cliente_id INT UNSIGNED NOT NULL,
  barbeiro_id INT UNSIGNED NOT NULL,
  servico_id INT UNSIGNED NOT NULL,
  horario DATETIME NOT NULL,
  status ENUM('confirmado', 'cancelado', 'concluido') DEFAULT 'confirmado',
  observacao VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (barbearia_id) REFERENCES barbearia(id),
  FOREIGN KEY (cliente_id) REFERENCES cliente(id),
  FOREIGN KEY (barbeiro_id) REFERENCES barbeiro(id),
  FOREIGN KEY (servico_id) REFERENCES servico(id)
);

CREATE TABLE horario_barbearia (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  barbearia_id INT UNSIGNED NOT NULL,
  dia_semana TINYINT NOT NULL, -- 0=domingo, 1=segunda ... 6=sabado
  hora_abertura TIME NOT NULL,
  hora_fechamento TIME NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (barbearia_id) REFERENCES barbearia(id)
);

CREATE TABLE horario_barbeiro (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  barbeiro_id INT UNSIGNED NOT NULL,
  dia_semana TINYINT NOT NULL, -- 0=domingo, 1=segunda ... 6=sabado
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (barbeiro_id) REFERENCES barbeiro(id)
);